version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fastapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fast_api
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    

  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:admin@db:3306/fast_api
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    links:
      - db

volumes:
  mysql_data:
